[package]
name = "routetbl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.11.4"
serde = { version = "1.0.151", features=["derive"] }